### PR TITLE
Don't write to stderr if PIL was not detected

### PR DESCRIPTION
**Pull request by rabbbit**
It's a valid use case to use svg's only.

### CODE REVIEW

**Comment by rabbbit** [comment]
please respond?
If the pull request is not valid, I'm happy to update it. 

I'd like to avoid forking whole thing ( which works very well ) just because of annoying lines being printed out :)

**Comment by kxepal** [comment]
Hi! Sorry, for delay.

Well, adding logging may be a bit brutal, but I'm fine with it now. Proper fix will require a bit package refactoring what I'm lazy to do, but since I accidentally have the first user so may be I should (:

Thanks!

**Comment by kxepal** [comment]
Btw the original project seems back to life: https://bitbucket.org/whitie/python-barcode/commits/all so may be you need to submit a fix to it as well.

**Comment by rabbbit** [comment]
Thanks! :)

The original project - hah, I looked https://pypi.python.org/pypi/pyBarcode/0.7 saw no code-128, then looked https://pypi.python.org/pypi/viivakoodi/0.8.0 and saw code-128, so I picked Viivakoodi. But, https://bitbucket.org/whitie/python-barcode/commits/all says they support code128.
So it looks like I maybe should've used pyBarcode ;)

First user - I wouldn't worry about refactoring - I really hope never to see/use/change/modify the barcode code again, so I won't be an active user :)

I guess I'll make a pull request on the original project too .. and then use whichever one of you pushes it to pypi first :)

**Pull request merged**
